export const GET_FALM_REQUET = "GET_FALM_REQUET"
export const GET_FALM_SUCCESS = "GET_FALM_SUCCESS"
export const GET_FALM_FAIL = "GET_FALM_FAIL"

// ! ===> id <===
export const GET_FALM_DETAILS_REQUEST = "GET_FALM_DETAILS_REQUEST";
export const GET_FALM_DETAILS_SUCCESS = "GET_FALM_DETAILS_SUCCESS";
export const GET_FALM_DETAILS_FAIL = "GET_FALM_DETAILS_FAIL";
export const GET_FALM_DETAILS_RESET = "GET_FALM_DETAILS_RESET";
